const manualLgaCorrections = {
    "abaji area council": "Abaji",
    "aboh mbaise": "Aboh-Mbaise",
    "abua odual": "Abua/Odual",
    "ado ekiti": "Ado-Ekiti",
    "ado odo ota": "Ado Odo/Ota",
    "ahiazu mbaise": "Ahiazu-Mbaise",
    "akawanga": "Akwanga",
    "akoko edo": "Akoko-Edo",
    "akuku toru": "Akuku Toru",
    "amuwo odofin": "Amuwo Odofin",
    "aniniri": "Aninri",
    "arewa": "Arewa Dandi",
    "askira uba": "Askira Uba",
    "atigbo": "Atisgbo",
    "ayadaade": "Ayedade",
    "bagudo": "Bagudu",
    "birnin magaji": "Birnin Magaji-Kiyaw",
    "birniwa": "Biriniwa",
    "bolowaduro": "Boluwaduro",
    "bwari area council": "Bwari",
    "chachanga": "Chanchaga",
    "damaboa": "Damboa",
    "damban": "Dambam",
    "danbatta": "Dambatta",
    "danmusa": "Dan Musa",
    "dawakin": "Dawakin Tofa",
    "dutsin ma": "Dutsin Ma",
    "edati idati": "Edati",
    "egbado north": "Yewa North",
    "egbado south": "Yewa South",
    "ehime mbano": "Ehime-Mbano",
    "ekiti south west": "Ekiti South-West",
    "emohua": "Emuoha",
    "esan north east": "Esan North-East",
    "esan south east": "Esan South-East",
    "ese odo": "Ese Odo",
    "eti osa": "Eti Osa",
    "gagara": "Gagarawa",
    "garum mallam": "Garun Mallam",
    "gerfi": "Girei",
    "gume": "Gumel",
    "gwagwa area council": "Gwagwa",
    "gwer east": "Gwer East",
    "gwer west": "Gwer West",
    "ibeju lekki": "Ibeju Lekki",
    "ido osi": "Ido-Osi",
    "ifako ijaye": "Ifako/Ijaye",
    "igo eze south": "Igbo-Eze-South",
    "igueben": "Iguegben",
    "ihite uboma": "Ihitte/Uboma",
    "ijebu ode": "Ijebu Ode",
    "ika north east": "Ika North East",
    "ikpoba okha": "Ikpoba-Okha",
    "ileoluji okeigbo": "Ile Oluji/Okeigbo",
    "ilesa east": "Ilesha East",
    "ilesa west": "Ilesha West",
    "isiala ngwa north": "Isiala-Ngwa North",
    "isiala ngwa south": "Isiala-Ngwa South",
    "isukwuato": "Isuikwuato",
    "itas gadau": "Itas/Gadau",
    "jama’are": "Jama'Are",
    "jaun": "Jahun",
    "jema’a": "Jema'A",
    "k hausa": "Kafin Hausa",
    "k kasamma": "Kiri Kasama",
    "k namoda": "Kaura Namoda",
    "kabba": "Kabba/Bunu",
    "karim lamido": "Karim Lamido",
    "koko besse": "Koko-Besse",
    "kuje area council": "Kuje",
    "kwali area council": "Kwali",
    "kwaya": "Kwaya Kusar",
    "lantang north": "Langtang North",
    "lantang south": "Langtang South",
    "m madori": "Malam Madori",
    "maiadua": "Mai'Adua",
    "maigatar": "Maigatari",
    "malumefashi": "Malumfashi",
    "markurdi": "Makurdi",
    "mashegu magama": "Magama",
    "mbaitoli": "Mbatoli",
    "metropolitan": "Maiduguri",
    "moguno": "Monguno",
    "mopamuro": "Mopa-Muro",
    "muya": "Munya",
    "nassarawa eggon": "Nasarawa Egon",
    "nganza": "Nganzai",
    "ngor okpala": "Ngor-Okpala",
    "nkwere": "Nkwerre",
    "obafemi owode": "Obafemi Owode",
    "obio akpor": "Obio/Akpor",
    "odo otin": "Odo Otin",
    "oji river": "Oji-River",
    "oke ero": "Oke Ero",
    "okirika": "Okrika",
    "ola oluwa": "Ola Oluwa",
    "omuma": "Omumma",
    "ona ara": "Ona Ara",
    "oorelope": "Orelope",
    "orire": "Ori Ire",
    "osisioma": "Osisioma Ngwa",
    "otukpo": "Oturkpo",
    "ovia north east": "Ovia North-East",
    "ovia south west": "Ovia South-West",
    "patigi": "Pategi",
    "port harcourt": "Port-Harcourt",
    "qua’an pan": "Qua'An Pan",
    "rimi gado": "Rimin Gado",
    "ringin": "Ringim",
    "s tankar": "Sule Tankarkar",
    "sagamu": "Shagamu",
    "shongom": "Shomgom",
    "t mafara": "Talata Mafara",
    "tafawa balewa": "Tafawa-Balewa",
    "tambuwa": "Tambuwal",
    "ugheli south": "Ughelli South",
    "uhunmwode": "Uhunmwonde",
    "ukwa west": "Ukwa West",
    "umunneochi": "Umu-Nneochi",
    "uzo uwani": "Uzo-Uwani",
    "warri south west": "Warri South-West",
    "wasagu danko": "Wasagu-Danko",
    "yenagoa": "Yenegoa",
    "zangon": "Zangon Kataf",
    "ukwa west and osisioma": ["Ukwa West", "Osisioma Ngwa"],
    "shongom": "Shomgom",  
    "markurdi": "Makurdi",
    "port harcourt": "Port Harcourt",
    "lanTANG": "Langtang", 
    "kwali area council": "Kwali",
    "obingwa": "Obi Nwga",
    "obi ngwa": "Obi Nwga",
    "gwagwa area council": "Gwagwalada",
    "gwagwa": "Gwagwalada",
    "shongom": "Shomgom",
    "garum mallam": "Garun Malam",
    "garun mallam": "Garun Malam",
    "kotangora": "Kontagora",
    "kontogora": "Kontagora",
    "atigbo": "Atisbo",
    "atisgbo": "Atisbo",
  };

export default manualLgaCorrections;
